2022-01-17 15:07:08,971 INFO    MainThread:5078 [wandb_setup.py:_flush():69] setting env: {}
2022-01-17 15:07:08,971 INFO    MainThread:5078 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '117529cf51086fe859b3f2bc348c7b486596477d'}
2022-01-17 15:07:08,971 INFO    MainThread:5078 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '117529cf51086fe859b3f2bc348c7b486596477d'}
2022-01-17 15:07:08,971 INFO    MainThread:5078 [wandb_setup.py:_flush():69] setting login settings: {}
2022-01-17 15:07:08,971 INFO    MainThread:5078 [wandb_init.py:_log_setup():342] Logging user logs to /Users/laurengreenspan/GitDLs/TreeNiNNew/code_ginkgo/recnn/wandb/run-20220117_150708-2rxbbpfv/logs/debug.log
2022-01-17 15:07:08,971 INFO    MainThread:5078 [wandb_init.py:_log_setup():343] Logging internal logs to /Users/laurengreenspan/GitDLs/TreeNiNNew/code_ginkgo/recnn/wandb/run-20220117_150708-2rxbbpfv/logs/debug-internal.log
2022-01-17 15:07:08,972 INFO    MainThread:5078 [wandb_init.py:init():375] calling init triggers
2022-01-17 15:07:08,972 INFO    MainThread:5078 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2022-01-17 15:07:08,972 INFO    MainThread:5078 [wandb_init.py:init():424] starting backend
2022-01-17 15:07:08,972 INFO    MainThread:5078 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-01-17 15:07:08,975 INFO    MainThread:5078 [backend.py:ensure_launched():135] starting backend process...
2022-01-17 15:07:08,988 ERROR   MainThread:5078 [wandb_init.py:init():801] error
Traceback (most recent call last):
  File "/Users/laurengreenspan/miniconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 775, in init
    run = wi.init()
  File "/Users/laurengreenspan/miniconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 427, in init
    backend.ensure_launched()
  File "/Users/laurengreenspan/miniconda3/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 137, in ensure_launched
    self.wandb_process.start()
  File "/Users/laurengreenspan/miniconda3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/laurengreenspan/miniconda3/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/laurengreenspan/miniconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/laurengreenspan/miniconda3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/laurengreenspan/miniconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/laurengreenspan/miniconda3/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/laurengreenspan/miniconda3/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
